
[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "HackGen Console NF"
style = "Bold"

[font.normal]
family = "HackGen Console NF"
style = "Regular"

[window]
opacity = 0.9

[window.padding]
x = 2
y = 0

[general]
import = ["/home/aijus/.config/alacritty/themes/themes/iterm.toml"]
